# Generated by Django 3.1.1 on 2020-09-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="catetory",
            new_name="category",
        ),
    ]
