# Generated by Django 3.1.1 on 2020-10-11 11:36

import django.db.models.deletion
from django.db import migrations, models

import helpers


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_auto_20200922_1713"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_images",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=helpers.fancy_id_generator,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(blank=True, upload_to="images")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
