# Generated by Django 3.1.1 on 2020-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_auto_20201011_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_images",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
