# Generated by Django 3.1.1 on 2020-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_remove_product_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_images",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
